name: "Push and Pull to Master"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - run: npm install
      - run: npm run jest
